/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fdz
 */
public class TelaSelecaoDupla extends javax.swing.JFrame {

    private int campo1;
    private int campo2;
    private TelaClientes telaClientes = null;
    private TelaContratos telaContratos = null;
    private TelaEnderecos telaEnderecos = null;
    private TelaFuncionarios telaFuncionarios = null;
    private TelaImoveis telaImoveis = null;
    private TelaImoveisItens telaImoveisItens = null;
    private TelaNivelAcessos telaNivelAcessos = null;
    private TelaOrcamentos telaOrcamentos = null;
    private TelaStatus telaStatus = null;
    private TelaTipoFuncionario telaTipoFuncionario = null;
    private TelaTipoImoveis telaTipoImoveis = null;
    private TelaTipoPagamento telaTipoPagamento = null;

    public TelaSelecaoDupla() {
        initComponents();
    }

    public TelaSelecaoDupla(TelaClientes telaClientes) {
        initComponents();
        this.telaClientes = telaClientes;
        popularComboBoxes(telaClientes.colunas);
    }

    public TelaSelecaoDupla(TelaContratos telaContratos) {
        initComponents();
        this.telaContratos = telaContratos;
        popularComboBoxes(telaContratos.colunas);
    }

    public TelaSelecaoDupla(TelaEnderecos telaEnderecos) {
        initComponents();
        this.telaEnderecos = telaEnderecos;
        popularComboBoxes(telaEnderecos.colunas);
    }

    public TelaSelecaoDupla(TelaFuncionarios telaFuncionarios) {
        initComponents();
        this.telaFuncionarios = telaFuncionarios;
        popularComboBoxes(telaFuncionarios.colunas);
    }

    public TelaSelecaoDupla(TelaImoveis telaImoveis) {
        initComponents();
        this.telaImoveis = telaImoveis;
        popularComboBoxes(telaImoveis.colunas);
    }

    public TelaSelecaoDupla(TelaImoveisItens telaImoveisItens) {
        initComponents();
        this.telaImoveisItens = telaImoveisItens;
        popularComboBoxes(telaImoveisItens.colunas);
    }

    public TelaSelecaoDupla(TelaNivelAcessos telaNivelAcessos) {
        initComponents();
        this.telaNivelAcessos = telaNivelAcessos;
        popularComboBoxes(telaNivelAcessos.colunas);
    }

    public TelaSelecaoDupla(TelaOrcamentos telaOrcamentos) {
        initComponents();
        this.telaOrcamentos = telaOrcamentos;
        popularComboBoxes(telaOrcamentos.colunas);
    }

    public TelaSelecaoDupla(TelaStatus telaStatus) {
        initComponents();
        this.telaStatus = telaStatus;
        popularComboBoxes(telaStatus.colunas);
    }

    public TelaSelecaoDupla(TelaTipoFuncionario telaTipoFuncionario) {
        initComponents();
        this.telaTipoFuncionario = telaTipoFuncionario;
        popularComboBoxes(telaTipoFuncionario.colunas);
    }

    public TelaSelecaoDupla(TelaTipoImoveis telaTipoImoveis) {
        initComponents();
        this.telaTipoImoveis = telaTipoImoveis;
        popularComboBoxes(telaTipoImoveis.colunas);
    }

    public TelaSelecaoDupla(TelaTipoPagamento telaTipoPagamento) {
        initComponents();
        this.telaTipoPagamento = telaTipoPagamento;
        popularComboBoxes(telaTipoPagamento.colunas);
    }

    private void popularComboBoxes(String[] colunas) {

        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();

        for (int i = 0; i < colunas.length; i++) {
            jComboBox1.addItem(colunas[i]);
            jComboBox2.addItem(colunas[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Selecao Dupla");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Primeiro critério de ordenação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Segundo critério de ordenação");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 48, 287, -1));

        jComboBox2.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(null);
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 287, -1));

        jPanel1.setBackground(new java.awt.Color(189, 209, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 190));

        jPanel2.setBackground(new java.awt.Color(205, 221, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSelecionar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSelecionar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonSelecionar.setForeground(new java.awt.Color(204, 204, 204));
        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.setBorder(null);
        jButtonSelecionar.setBorderPainted(false);
        jButtonSelecionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSelecionar.setFocusPainted(false);
        jButtonSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSelecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSelecionarMouseExited(evt);
            }
        });
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 350, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed

        try {
            campo1 = jComboBox1.getSelectedIndex();
            campo2 = jComboBox2.getSelectedIndex();

            if (telaClientes != null) {
                telaClientes.popularJtableDupla(campo1, campo2);
            }
            if (telaContratos != null) {
                telaContratos.popularJtableDupla(campo1, campo2);
            }
            if (telaEnderecos != null) {
                telaEnderecos.popularJtableDupla(campo1, campo2);
            }
            if (telaFuncionarios != null) {
                telaFuncionarios.popularJtableDupla(campo1, campo2);
            }
            if (telaImoveis != null) {
                telaImoveis.popularJtableDupla(campo1, campo2);
            }
            if (telaImoveisItens != null) {
                telaImoveisItens.popularJtableDupla(campo1, campo2);
            }
            if (telaNivelAcessos != null) {
                telaNivelAcessos.popularJtableDupla(campo1, campo2);
            }
            if (telaOrcamentos != null) {
                telaOrcamentos.popularJtableDupla(campo1, campo2);
            }
            if (telaStatus != null) {
                telaStatus.popularJtableDupla(campo1, campo2);
            }
            if (telaTipoFuncionario != null) {
                telaTipoFuncionario.popularJtableDupla(campo1, campo2);
            }
            if (telaTipoImoveis != null) {
                telaTipoImoveis.popularJtableDupla(campo1, campo2);
            }
            if (telaTipoPagamento != null) {
                telaTipoPagamento.popularJtableDupla(campo1, campo2);
            }
            
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonSelecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSelecionarMouseEntered
        if (jButtonSelecionar.isEnabled())
            jButtonSelecionar.setBackground(new Color(52,52,52));
    }//GEN-LAST:event_jButtonSelecionarMouseEntered

    private void jButtonSelecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSelecionarMouseExited
        if (jButtonSelecionar.isEnabled())
            jButtonSelecionar.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButtonSelecionarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoDupla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoDupla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoDupla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoDupla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSelecaoDupla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
