/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.awt.Color;
import java.sql.Array;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Funcionario;
import model.Usuario;
import util.GeradorPasswords;
import util.Login;

/**
 *
 * @author fdz
 */
public class TelaMenu extends javax.swing.JFrame {

    private Funcionario funcionario = null;

    public TelaMenu() {
        initComponents();
        iniciar();
    }

    private void iniciar() {
        try {

            jButtonClientes.setVisible(false);
            jButtonContratos.setVisible(false);
            jButtonEnderecos.setVisible(false);
            jButtonFuncionarios.setVisible(false);
            jButtonImoveis.setVisible(false);
            jButtonNiveisDeAcesso.setVisible(false);
            jButtonOrcamentos.setVisible(false);
            jButtonStatus.setVisible(false);
            jButtonTiposDeFuncionarios.setVisible(false);
            jButtonTiposDeImovel.setVisible(false);
            jButtonTiposDePagamento.setVisible(false);
            jButtonRelatorios.setVisible(false);

            funcionario = Login.funcionario;
            Array permissoes = funcionario.getTipoFuncionario().getNivelAcesso().getNivel();

            jLabelFuncionarioAtual.setText(funcionario.getNome());
            permitirBotoes(permissoes);
        } catch (Exception e) {

        }
    }

    private void permitirBotoes(Array permissoes) throws SQLException {
        Integer[] niveis = (Integer[]) permissoes.getArray();

        if (niveis[0] == 1) {
            jButtonClientes.setVisible(true);
        }
        if (niveis[1] == 1) {
            jButtonContratos.setVisible(true);
        }
        if (niveis[2] == 1) {
            jButtonEnderecos.setVisible(true);
        }
        if (niveis[3] == 1) {
            jButtonFuncionarios.setVisible(true);
        }
        if (niveis[4] == 1) {
            jButtonImoveis.setVisible(true);
        }
        if (niveis[6] == 1) {
            jButtonNiveisDeAcesso.setVisible(true);
        }
        if (niveis[7] == 1) {
            jButtonOrcamentos.setVisible(true);
        }
        if (niveis[8] == 1) {
            jButtonStatus.setVisible(true);
        }
        if (niveis[9] == 1) {
            jButtonTiposDeFuncionarios.setVisible(true);
        }
        if (niveis[10] == 1) {
            jButtonTiposDeImovel.setVisible(true);
        }
        if (niveis[11] == 1) {
            jButtonTiposDePagamento.setVisible(true);
        }
        if (niveis[12] == 1) {
            jButtonRelatorios.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButtonNiveisDeAcesso = new javax.swing.JButton();
        jButtonTiposDeFuncionarios = new javax.swing.JButton();
        jButtonFuncionarios = new javax.swing.JButton();
        jButtonEnderecos = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonRelatorios = new javax.swing.JButton();
        jButtonImoveis = new javax.swing.JButton();
        jButtonTiposDeImovel = new javax.swing.JButton();
        jButtonStatus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonLogOff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFuncionarioAtual = new javax.swing.JLabel();
        jButtonTrocaDeSenha = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonTiposDePagamento = new javax.swing.JButton();
        jButtonOrcamentos = new javax.swing.JButton();
        jButtonContratos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 209, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNiveisDeAcesso.setBackground(new java.awt.Color(102, 102, 102));
        jButtonNiveisDeAcesso.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonNiveisDeAcesso.setForeground(new java.awt.Color(204, 204, 204));
        jButtonNiveisDeAcesso.setText("Niveis de acesso");
        jButtonNiveisDeAcesso.setBorder(null);
        jButtonNiveisDeAcesso.setBorderPainted(false);
        jButtonNiveisDeAcesso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNiveisDeAcesso.setFocusPainted(false);
        jButtonNiveisDeAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNiveisDeAcessoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNiveisDeAcessoMouseExited(evt);
            }
        });
        jButtonNiveisDeAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNiveisDeAcessoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNiveisDeAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 50));

        jButtonTiposDeFuncionarios.setBackground(new java.awt.Color(102, 102, 102));
        jButtonTiposDeFuncionarios.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonTiposDeFuncionarios.setForeground(new java.awt.Color(204, 204, 204));
        jButtonTiposDeFuncionarios.setText("Tipos de funcionario");
        jButtonTiposDeFuncionarios.setBorder(null);
        jButtonTiposDeFuncionarios.setBorderPainted(false);
        jButtonTiposDeFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTiposDeFuncionarios.setFocusPainted(false);
        jButtonTiposDeFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTiposDeFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTiposDeFuncionariosMouseExited(evt);
            }
        });
        jButtonTiposDeFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiposDeFuncionariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTiposDeFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 50));

        jButtonFuncionarios.setBackground(new java.awt.Color(102, 102, 102));
        jButtonFuncionarios.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonFuncionarios.setForeground(new java.awt.Color(204, 204, 204));
        jButtonFuncionarios.setText("Funcionarios");
        jButtonFuncionarios.setBorder(null);
        jButtonFuncionarios.setBorderPainted(false);
        jButtonFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFuncionarios.setFocusPainted(false);
        jButtonFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonFuncionariosMouseExited(evt);
            }
        });
        jButtonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, 50));

        jButtonEnderecos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEnderecos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonEnderecos.setForeground(new java.awt.Color(204, 204, 204));
        jButtonEnderecos.setText("Enderecos");
        jButtonEnderecos.setBorder(null);
        jButtonEnderecos.setBorderPainted(false);
        jButtonEnderecos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnderecos.setFocusPainted(false);
        jButtonEnderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEnderecosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEnderecosMouseExited(evt);
            }
        });
        jButtonEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnderecosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEnderecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 50));

        jButtonClientes.setBackground(new java.awt.Color(102, 102, 102));
        jButtonClientes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonClientes.setForeground(new java.awt.Color(204, 204, 204));
        jButtonClientes.setText("Clientes");
        jButtonClientes.setBorder(null);
        jButtonClientes.setBorderPainted(false);
        jButtonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClientes.setFocusPainted(false);
        jButtonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonClientesMouseExited(evt);
            }
        });
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_person_50px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 420));

        jPanel2.setBackground(new java.awt.Color(189, 209, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRelatorios.setBackground(new java.awt.Color(102, 102, 102));
        jButtonRelatorios.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonRelatorios.setForeground(new java.awt.Color(204, 204, 204));
        jButtonRelatorios.setText("Relatórios");
        jButtonRelatorios.setBorder(null);
        jButtonRelatorios.setBorderPainted(false);
        jButtonRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRelatorios.setFocusPainted(false);
        jButtonRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRelatoriosMouseExited(evt);
            }
        });
        jButtonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatoriosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 50));

        jButtonImoveis.setBackground(new java.awt.Color(102, 102, 102));
        jButtonImoveis.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonImoveis.setForeground(new java.awt.Color(204, 204, 204));
        jButtonImoveis.setText("Imoveis");
        jButtonImoveis.setBorder(null);
        jButtonImoveis.setBorderPainted(false);
        jButtonImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonImoveis.setFocusPainted(false);
        jButtonImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonImoveisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonImoveisMouseExited(evt);
            }
        });
        jButtonImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImoveisActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonImoveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 170, 50));

        jButtonTiposDeImovel.setBackground(new java.awt.Color(102, 102, 102));
        jButtonTiposDeImovel.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonTiposDeImovel.setForeground(new java.awt.Color(204, 204, 204));
        jButtonTiposDeImovel.setText("Tipos de imovel");
        jButtonTiposDeImovel.setBorder(null);
        jButtonTiposDeImovel.setBorderPainted(false);
        jButtonTiposDeImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTiposDeImovel.setFocusPainted(false);
        jButtonTiposDeImovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTiposDeImovelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTiposDeImovelMouseExited(evt);
            }
        });
        jButtonTiposDeImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiposDeImovelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTiposDeImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, 50));

        jButtonStatus.setBackground(new java.awt.Color(102, 102, 102));
        jButtonStatus.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonStatus.setForeground(new java.awt.Color(204, 204, 204));
        jButtonStatus.setText("Status");
        jButtonStatus.setBorder(null);
        jButtonStatus.setBorderPainted(false);
        jButtonStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStatus.setFocusPainted(false);
        jButtonStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonStatusMouseExited(evt);
            }
        });
        jButtonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_business_building_50px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 270, 420));

        jPanel3.setBackground(new java.awt.Color(102, 136, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogOff.setBackground(new java.awt.Color(102, 102, 102));
        jButtonLogOff.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonLogOff.setForeground(new java.awt.Color(204, 204, 204));
        jButtonLogOff.setText("Log off");
        jButtonLogOff.setBorder(null);
        jButtonLogOff.setBorderPainted(false);
        jButtonLogOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogOff.setFocusPainted(false);
        jButtonLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogOffMouseExited(evt);
            }
        });
        jButtonLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOffActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 170, 50));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Bem-vindo ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 26));

        jLabelFuncionarioAtual.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabelFuncionarioAtual.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jLabelFuncionarioAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 262, 26));

        jButtonTrocaDeSenha.setBackground(new java.awt.Color(102, 102, 102));
        jButtonTrocaDeSenha.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonTrocaDeSenha.setForeground(new java.awt.Color(204, 204, 204));
        jButtonTrocaDeSenha.setText("Trocar Senha");
        jButtonTrocaDeSenha.setBorder(null);
        jButtonTrocaDeSenha.setBorderPainted(false);
        jButtonTrocaDeSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTrocaDeSenha.setFocusPainted(false);
        jButtonTrocaDeSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTrocaDeSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTrocaDeSenhaMouseExited(evt);
            }
        });
        jButtonTrocaDeSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrocaDeSenhaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonTrocaDeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 170, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 130));

        jPanel4.setBackground(new java.awt.Color(205, 221, 228));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTiposDePagamento.setBackground(new java.awt.Color(102, 102, 102));
        jButtonTiposDePagamento.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonTiposDePagamento.setForeground(new java.awt.Color(204, 204, 204));
        jButtonTiposDePagamento.setText("Tipos de pagamento");
        jButtonTiposDePagamento.setBorder(null);
        jButtonTiposDePagamento.setBorderPainted(false);
        jButtonTiposDePagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTiposDePagamento.setFocusPainted(false);
        jButtonTiposDePagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTiposDePagamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTiposDePagamentoMouseExited(evt);
            }
        });
        jButtonTiposDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiposDePagamentoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonTiposDePagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, 50));

        jButtonOrcamentos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonOrcamentos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonOrcamentos.setForeground(new java.awt.Color(204, 204, 204));
        jButtonOrcamentos.setText("Orcamentos");
        jButtonOrcamentos.setBorder(null);
        jButtonOrcamentos.setBorderPainted(false);
        jButtonOrcamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOrcamentos.setFocusPainted(false);
        jButtonOrcamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOrcamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOrcamentosMouseExited(evt);
            }
        });
        jButtonOrcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrcamentosActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonOrcamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, 50));

        jButtonContratos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonContratos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButtonContratos.setForeground(new java.awt.Color(204, 204, 204));
        jButtonContratos.setText("Contratos");
        jButtonContratos.setBorder(null);
        jButtonContratos.setBorderPainted(false);
        jButtonContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContratos.setFocusPainted(false);
        jButtonContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContratosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContratosMouseExited(evt);
            }
        });
        jButtonContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContratosActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_sell_50px.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 50, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 280, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionariosActionPerformed
        try {
            new TelaFuncionarios().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonFuncionariosActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        try {
            new TelaClientes().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnderecosActionPerformed
        try {
            new TelaEnderecos().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEnderecosActionPerformed

    private void jButtonTiposDeFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiposDeFuncionariosActionPerformed
        try {
            new TelaTipoFuncionario().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTiposDeFuncionariosActionPerformed

    private void jButtonNiveisDeAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNiveisDeAcessoActionPerformed
        try {
            new TelaNivelAcessos().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonNiveisDeAcessoActionPerformed

    private void jButtonOrcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrcamentosActionPerformed
        try {
            new TelaOrcamentos().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonOrcamentosActionPerformed

    private void jButtonTiposDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiposDePagamentoActionPerformed
        try {
            new TelaTipoPagamento().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTiposDePagamentoActionPerformed

    private void jButtonLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOffActionPerformed

        Object[] options = {"Confirmar", "Cancelar"};
        int opcao = JOptionPane.showOptionDialog(null, "Clique Confirmar para continuar", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (opcao == 0) {
            Login.funcionario = null;
            new TelaLogin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButtonLogOffActionPerformed

    private void jButtonImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImoveisActionPerformed
        try {
            new TelaImoveis().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonImoveisActionPerformed

    private void jButtonTiposDeImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiposDeImovelActionPerformed
        try {
            new TelaTipoImoveis().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTiposDeImovelActionPerformed

    private void jButtonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusActionPerformed
        try {
            new TelaStatus().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonStatusActionPerformed

    private void jButtonContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratosActionPerformed
        try {
            new TelaContratos().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonContratosActionPerformed

    private void jButtonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatoriosActionPerformed
        try {
            new TelaRelatorios().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonRelatoriosActionPerformed

    private void jButtonFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFuncionariosMouseEntered
        jButtonFuncionarios.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonFuncionariosMouseEntered

    private void jButtonFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFuncionariosMouseExited
        jButtonFuncionarios.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonFuncionariosMouseExited

    private void jButtonClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClientesMouseEntered
        jButtonClientes.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonClientesMouseEntered

    private void jButtonClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClientesMouseExited
        jButtonClientes.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonClientesMouseExited

    private void jButtonEnderecosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnderecosMouseEntered
        jButtonEnderecos.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonEnderecosMouseEntered

    private void jButtonEnderecosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnderecosMouseExited
        jButtonEnderecos.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonEnderecosMouseExited

    private void jButtonTiposDeFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiposDeFuncionariosMouseEntered
        jButtonTiposDeFuncionarios.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonTiposDeFuncionariosMouseEntered

    private void jButtonTiposDeFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiposDeFuncionariosMouseExited
        jButtonTiposDeFuncionarios.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonTiposDeFuncionariosMouseExited

    private void jButtonNiveisDeAcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNiveisDeAcessoMouseEntered
        jButtonNiveisDeAcesso.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonNiveisDeAcessoMouseEntered

    private void jButtonNiveisDeAcessoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNiveisDeAcessoMouseExited
        jButtonNiveisDeAcesso.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonNiveisDeAcessoMouseExited

    private void jButtonOrcamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrcamentosMouseEntered
        jButtonOrcamentos.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonOrcamentosMouseEntered

    private void jButtonOrcamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrcamentosMouseExited
        jButtonOrcamentos.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonOrcamentosMouseExited

    private void jButtonTiposDePagamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiposDePagamentoMouseEntered
        jButtonTiposDePagamento.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonTiposDePagamentoMouseEntered

    private void jButtonTiposDePagamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiposDePagamentoMouseExited
        jButtonTiposDePagamento.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonTiposDePagamentoMouseExited

    private void jButtonContratosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContratosMouseEntered
        jButtonContratos.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonContratosMouseEntered

    private void jButtonContratosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContratosMouseExited
        jButtonContratos.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonContratosMouseExited

    private void jButtonLogOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogOffMouseEntered
        jButtonLogOff.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonLogOffMouseEntered

    private void jButtonLogOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogOffMouseExited
        jButtonLogOff.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonLogOffMouseExited

    private void jButtonRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelatoriosMouseEntered
        jButtonRelatorios.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonRelatoriosMouseEntered

    private void jButtonRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelatoriosMouseExited
        jButtonRelatorios.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonRelatoriosMouseExited

    private void jButtonImoveisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImoveisMouseEntered
        jButtonImoveis.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonImoveisMouseEntered

    private void jButtonImoveisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImoveisMouseExited
        jButtonImoveis.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonImoveisMouseExited

    private void jButtonTiposDeImovelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiposDeImovelMouseEntered
        jButtonTiposDeImovel.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonTiposDeImovelMouseEntered

    private void jButtonTiposDeImovelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiposDeImovelMouseExited
        jButtonTiposDeImovel.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonTiposDeImovelMouseExited

    private void jButtonStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStatusMouseEntered
        jButtonStatus.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonStatusMouseEntered

    private void jButtonStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStatusMouseExited
        jButtonStatus.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonStatusMouseExited

    private void jButtonTrocaDeSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTrocaDeSenhaMouseEntered
        jButtonTrocaDeSenha.setBackground(new Color(52, 52, 52));
    }//GEN-LAST:event_jButtonTrocaDeSenhaMouseEntered

    private void jButtonTrocaDeSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTrocaDeSenhaMouseExited
        jButtonTrocaDeSenha.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonTrocaDeSenhaMouseExited

    private void jButtonTrocaDeSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrocaDeSenhaActionPerformed

        try {
            UsuarioController usuCon = new UsuarioController();

            Usuario user = usuCon.getItemComLoginPorEmail(Login.funcionario.getEmail());
            String novaSenha = "";

            while (novaSenha.equals("")) {
                novaSenha = JOptionPane.showInputDialog("Digite a nova senha");
                if (novaSenha.equals("")) {
                    JOptionPane.showMessageDialog(this, "Por favor digite algo no campo de senha");
                }
            }

            user.setSenha(GeradorPasswords.generateSecurePassword(novaSenha, "Pacoca"));
            new UsuarioController().alterarItem(user);

            JOptionPane.showMessageDialog(this, "Senha alterada com sucesso");

        } catch (Exception ex) {
            Logger.getLogger(TelaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTrocaDeSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonContratos;
    private javax.swing.JButton jButtonEnderecos;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonImoveis;
    private javax.swing.JButton jButtonLogOff;
    private javax.swing.JButton jButtonNiveisDeAcesso;
    private javax.swing.JButton jButtonOrcamentos;
    private javax.swing.JButton jButtonRelatorios;
    private javax.swing.JButton jButtonStatus;
    private javax.swing.JButton jButtonTiposDeFuncionarios;
    private javax.swing.JButton jButtonTiposDeImovel;
    private javax.swing.JButton jButtonTiposDePagamento;
    private javax.swing.JButton jButtonTrocaDeSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFuncionarioAtual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
